import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-[70px] bg-red-500 shadow-lg  container border-b mx-auto flex items-center justify-start">
          <p className=" text-white  text-xl font-bold  ">PDF Generater</p>
        </div>
        {children}
      </body>
    </html>
  );
}
